export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const POSTS_LOADED = "POSTS_LOADED";

export const PWD_REQUEST_SUCCESS = "PWD_REQUEST_SUCCESS";

export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAILURE = "USER_LOAD_FAILURE";
export const USER_FOLLOWED = "USER_FOLLOWED";
export const PROFILE_UPDATED = "PROFILE_UPDATED";

export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAILURE = "PROJECT_CREATE_FAILURE";
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAILURE = "PROJECT_DELETE_FAILURE";
export const PROJECT_LOAD_SUCCESS = "PROJECT_LOAD_SUCCESS";
export const PROJECT_LOAD_FAILURE = "PROJECT_LOAD_FAILURE";
export const PROJECT_EDIT_SUCCESS = "PROJECT_EDIT_SUCCESS";
export const PROJECT_EDIT_FAILURE = "PROJECT_EDIT_FAILURE";
export const PROJECT_INITCANVASCONNECTION_SUCCESS = "PROJECT_INITCANVASCONNECTION_SUCCESS";
export const PROJECT_INITCANVASCONNECTION_FAILURE = "PROJECT_INITCANVASCONNECTION_FAILURE";
export const PROJECT_EDITINGSTATUSUPDATE_SUCCESS = "PROJECT_EDITINGSTATUSUPDATE_SUCCESS";
export const PROJECT_EDITINGSTATUSUPDATE_FAILURE = "PROJECT_EDITINGSTATUSUPDATE_FAILURE";
export const PROJECT_EXPORT_SUCCESS = "PROJECT_EXPORT_SUCCESS";
export const PROJECT_EXPORT_FAILURE = "PROJECT_EXPORT_FAILURE";
export const PROJECT_PERMISSIONCHANGE_SUCCESS = "PROJECT_PERMISSIONCHANGE_SUCCESS";
export const PROJECT_PERMISSIONCHANGE_FAILURE = "PROJECT_PERMISSIONCHANGE_FAILURE";

export const PAGE_ADD_SUCCESS = "PAGE_ADD_SUCCESS";
export const PAGE_ADD_FAILURE = "PAGE_ADD_FAILURE";
export const PAGE_DELETE_SUCCESS = "PAGE_DELETE_SUCCESS";
export const PAGE_DELETE_FAILURE = "PAGE_DELETE_FAILURE";
export const PAGE_LOAD_SUCCESS = "PAGE_LOAD_SUCCESS";
export const PAGE_LOAD_FAILURE = "PAGE_LOAD_FAILURE";
export const PAGE_EDIT_SUCCESS = "PAGE_EDIT_SUCCESS";
export const PAGE_EDIT_FAILURE = "PAGE_EDIT_FAILURE";

export const AWS_SIGNEDURL_SUCCESS = "AWS_SIGNEDURL_SUCCESS";
export const AWS_SIGNEDURL_FAILURE = "AWS_SIGNEDURL_FAILURE";
export const AWS_UPLOAD_SUCCESS = "AWS_UPLOAD_SUCCESS";
export const AWS_UPLOAD_FAILURE = "AWS_UPLOAD_FAILURE";
export const ADD_PAGE = "ADD_PAGE";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE";
export const SET_EDITING_PAGE = "SET_EDITING_PAGE";
export const DELETE_PAGE = "DELETE_PAGE";
